# Generated by Django 2.2.6 on 2019-10-04 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_created', models.DateField(auto_now_add=True, db_index=True)),
                ('slug', models.SlugField(max_length=200, unique_for_date='date_created')),
                ('date_due', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(choices=[(1, 'high'), (2, 'medium'), (3, 'low')], default=2)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-date_due', 'title'],
            },
        ),
    ]
