# Generated by Django 2.2.6 on 2019-10-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('slug', 'date_due')},
        ),
    ]
