# Generated by Django 2.2.6 on 2019-10-05 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0003_auto_20191004_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-priority', 'date_due', 'title']},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('slug', 'date_due', 'user')},
        ),
    ]
