# Generated by Django 2.2.6 on 2019-10-05 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0004_auto_20191005_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('slug', 'date_created', 'user')},
        ),
    ]
